// Code generated by protoc-gen-ginsev. DO NOT EDIT.

package api

import (
	gin "github.com/gin-gonic/gin"
)

// blog service is a blog demo
type BlogService interface {
	GetArticles(c *gin.Context)
	CreateArticle(c *gin.Context)
	GetArticlePost(c *gin.Context)
	Articles(c *gin.Context)
	UnionArticle(c *gin.Context)
}

// RegisterBlogService register router
func RegisterBlogService(router gin.IRouter, service BlogService) {
	router.Handle("GET", "/v1/articles", service.GetArticles)
	router.Handle("POST", "/v1/author/{author_id}/articles", service.CreateArticle)
	router.Handle("GET", "blog/getArticlePost", service.GetArticlePost)
	router.Handle("POST", "blog/articles", service.Articles)
	router.Handle("POST", "blog/unionArticle", service.UnionArticle)
}
