// Code generated by protoc-gen-ginsev. DO NOT EDIT.

package api

import (
	gin "github.com/gin-gonic/gin"
)

type EvaluateService interface {
	// 创建评测任务
	CreateTask(c *gin.Context)
	// 评测任务列表
	ListTask(c *gin.Context)
	// 评测任务详情
	GetTask(c *gin.Context)
	// 更新评测任务
	UpdateTask(c *gin.Context)
	// 删除评测任务
	DeleteTask(c *gin.Context)
	// 取消评测任务
	CancelTask(c *gin.Context)
	// 重试任务
	RetryTask(c *gin.Context)
}

// RegisterEvaluateService register router
func RegisterEvaluateService(router gin.IRouter, service EvaluateService) {
	router.Handle("POST", "/api/models/evaluate", service.CreateTask)
	router.Handle("GET", "/api/models/evaluate", service.ListTask)
	router.Handle("GET", "/api/models/evaluate/:taskID", service.GetTask)
	router.Handle("POST", "/api/models/evaluate/:taskID", service.UpdateTask)
	router.Handle("DELETE", "/api/models/evaluate/:taskID", service.DeleteTask)
	router.Handle("POST", "/api/models/evaluate/:taskID", service.CancelTask)
	router.Handle("POST", "/api/models/evaluate/:taskID", service.RetryTask)
}
